/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Levels3RouteImport } from './routes/levels/3'
import { Route as Levels2RouteImport } from './routes/levels/2'
import { Route as Levels1RouteImport } from './routes/levels/1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Levels3Route = Levels3RouteImport.update({
  id: '/levels/3',
  path: '/levels/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Levels2Route = Levels2RouteImport.update({
  id: '/levels/2',
  path: '/levels/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Levels1Route = Levels1RouteImport.update({
  id: '/levels/1',
  path: '/levels/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels/1': typeof Levels1Route
  '/levels/2': typeof Levels2Route
  '/levels/3': typeof Levels3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels/1': typeof Levels1Route
  '/levels/2': typeof Levels2Route
  '/levels/3': typeof Levels3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels/1': typeof Levels1Route
  '/levels/2': typeof Levels2Route
  '/levels/3': typeof Levels3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/levels/1' | '/levels/2' | '/levels/3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels/1' | '/levels/2' | '/levels/3'
  id: '__root__' | '/' | '/levels/1' | '/levels/2' | '/levels/3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Levels1Route: typeof Levels1Route
  Levels2Route: typeof Levels2Route
  Levels3Route: typeof Levels3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/3': {
      id: '/levels/3'
      path: '/levels/3'
      fullPath: '/levels/3'
      preLoaderRoute: typeof Levels3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/2': {
      id: '/levels/2'
      path: '/levels/2'
      fullPath: '/levels/2'
      preLoaderRoute: typeof Levels2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/1': {
      id: '/levels/1'
      path: '/levels/1'
      fullPath: '/levels/1'
      preLoaderRoute: typeof Levels1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Levels1Route: Levels1Route,
  Levels2Route: Levels2Route,
  Levels3Route: Levels3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
